src/AideBundle/Entity/Candidature.php
<?php

/* This file is part of AIDE

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

namespace AideBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Candidature
 */
class Candidature
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $mdp;

    /**
     * @var boolean
     */
    private $vaa;

    /**
     * @var boolean
     */
    private $annule;

    /**
     * @var \DateTime
     */
    private $date_fabrication;

    /**
     * @var \DateTime
     */
    private $date_reception;

    /**
     * @var \DateTime
     */
    private $date_validation;

    /**
     * @var \DateTime
     */
    private $date_decision;

    /**
     * @var string
     */
    private $pieces_manquantes_libres;

    protected $pieces_manquantes;
    protected $candidat;
    //protected $campagne;
    protected $formation;
    protected $resultat;
    protected $statut;
    protected $convocation;
    private $motif_refus;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->pieces_manquantes = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set mdp
     *
     * @param string $mdp
     * @return Candidature
     */
    public function setMdp($mdp)
    {
        $this->mdp = $mdp;

        return $this;
    }

    /**
     * Get mdp
     *
     * @return string
     */
    public function getMdp()
    {
        return $this->mdp;
    }

    /**
     * Set vaa
     *
     * @param boolean $vaa
     * @return Candidature
     */
    public function setVaa($vaa)
    {
        $this->vaa = $vaa;

        return $this;
    }

    /**
     * Get vaa
     *
     * @return boolean
     */
    public function getVaa()
    {
        return $this->vaa;
    }

    /**
     * Set annule
     *
     * @param boolean $annule
     * @return Candidature
     */
    public function setAnnule($annule)
    {
        $this->annule = $annule;

        return $this;
    }

    /**
     * Get annule
     *
     * @return boolean
     */
    public function getAnnule()
    {
        return $this->annule;
    }

    /**
     * Set date_fabrication
     *
     * @param \DateTime $dateFabrication
     * @return Candidature
     */
    public function setDateFabrication($dateFabrication)
    {
        $this->date_fabrication = $dateFabrication;

        return $this;
    }

    /**
     * Get date_fabrication
     *
     * @return \DateTime
     */
    public function getDateFabrication()
    {
        return $this->date_fabrication;
    }

    /**
     * Set date_reception
     *
     * @param \DateTime $dateReception
     * @return Candidature
     */
    public function setDateReception($dateReception)
    {
        $this->date_reception = $dateReception;

        return $this;
    }

    /**
     * Get date_reception
     *
     * @return \DateTime
     */
    public function getDateReception()
    {
        return $this->date_reception;
    }

    /**
     * Set date_validation
     *
     * @param \DateTime $dateValidation
     * @return Candidature
     */
    public function setDateValidation($dateValidation)
    {
        $this->date_validation = $dateValidation;

        return $this;
    }

    /**
     * Get date_validation
     *
     * @return \DateTime
     */
    public function getDateValidation()
    {
        return $this->date_validation;
    }

    /**
     * Set date_decision
     *
     * @param \DateTime $dateDecision
     * @return Candidature
     */
    public function setDateDecision($dateDecision)
    {
        $this->date_decision = $dateDecision;

        return $this;
    }

    /**
     * Get date_decision
     *
     * @return \DateTime
     */
    public function getDateDecision()
    {
        return $this->date_decision;
    }

    /**
     * Set pieces_manquantes_libres
     *
     * @param string $pieces_manquantes_libres
     * @return Candidature
     */
    public function setPiecesManquantesLibres($pieces_manquantes_libres)
    {
        $this->pieces_manquantes_libres = $pieces_manquantes_libres;

        return $this;
    }

    /**
     * Get pieces_manquantes_libres
     *
     * @return string
     */
    public function getPiecesManquantesLibres()
    {
        return $this->pieces_manquantes_libres;
    }

    /**
     * Add piece_manquante
     *
     * @param \AideBundle\Entity\PieceJointe $piece_manquante
     * @return Candidat
     */
    public function addPieceManquante(\AideBundle\Entity\PieceJointe $piece_manquante)
    {
        if ($this -> hasPieceManquante($piece_manquante)) return $this;
        $this->pieces_manquantes[] = $piece_manquante;
        return $this;
    }

    /**
     * Remove piece_manquante
     *
     * @param \AideBundle\Entity\PieceJointe $piece_manquante
     */
    public function removePieceManquante(\AideBundle\Entity\PieceJointe $piece_manquante)
    {
        $this->pieces_manquantes->removeElement($piece_manquante);
    }

    /**
     * Has piece_manquante
     *
     * @return boolean
     */
    public function hasPieceManquante($pj)
    {
        return $this -> pieces_manquantes -> contains($pj);
    }

    /**
     * Get pieces_manquantes
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPiecesManquantes()
    {
        return $this->pieces_manquantes;
    }

    /**
     * Get codes des pieces_manquantes
     *
     * @return array
     */
    public function getCodesPiecesManquantes()
    {
	$ret = array();
        foreach ($this->pieces_manquantes as $pm) $ret[] = $pm -> getCode();
	return $ret;
    }

    /**
     * Set candidat
     *
     * @param \AideBundle\Entity\Candidat $candidat
     * @return Candidature
     */
    public function setCandidat(\AideBundle\Entity\Candidat $candidat = null)
    {
        $this->candidat = $candidat;

        return $this;
    }

    /**
     * Get candidat
     *
     * @return \AideBundle\Entity\Candidat
     */
    public function getCandidat()
    {
        return $this->candidat;
    }

    /**
     * Set campagne
     *
     * @param \AideBundle\Entity\Campagne $campagne
     * @return Candidature
     */
/*    public function setCampagne(\AideBundle\Entity\Campagne $campagne = null)
    {
        $this->campagne = $campagne;

        return $this;
    } */

    /**
     * Get campagne
     *
     * @return \AideBundle\Entity\Campagne
     */
/*    public function getCampagne()
    {
        return $this->campagne;
    } */

    /**
     * Set formation
     *
     * @param \AideBundle\Entity\Formation $formation
     * @return Candidature
     */
    public function setFormation(\AideBundle\Entity\Formation $formation = null)
    {
        $this->formation = $formation;

        return $this;
    }

    /**
     * Get formation
     *
     * @return \AideBundle\Entity\Formation
     */
    public function getFormation()
    {
        return $this->formation;
    }

    /**
     * Set resultat
     *
     * @param \AideBundle\Entity\Resultat $resultat
     * @return Candidature
     */
    public function setResultat(\AideBundle\Entity\Resultat $resultat = null)
    {
        $this->resultat = $resultat;

        return $this;
    }

    /**
     * Get resultat
     *
     * @return \AideBundle\Entity\Resultat
     */
    public function getResultat()
    {
        return $this->resultat;
    }

    /**
     * Set motif_refus
     *
     * @param \AideBundle\Entity\Motif $motif
     * @return Candidature
     */
    public function setMotifRefus(\AideBundle\Entity\Motif $motif = null)
    {
        $this->motif_refus = $motif;

        return $this;
    }

    /**
     * Get motif_refus
     *
     * @return \AideBundle\Entity\Motif
     */
    public function getMotifRefus()
    {
        return $this->motif_refus;
    }


    /**
     * Set convocation
     *
     * @param \AideBundle\Entity\Convocation $convocation
     * @return Candidature
     */
    public function setConvocation(\AideBundle\Entity\Convocation $convocation = null)
    {
        $this->convocation = $convocation;

        return $this;
    }

    /**
     * Get convocation
     *
     * @return \AideBundle\Entity\Convocation
     */
    public function getConvocation()
    {
        return $this->convocation;
    }


    public function setStatut() {
        $this -> statut = "téléch.";
   }

}

src/AideBundle/Resources/views/Backoffice/admission.html.twig
{% extends '::suivi.html.twig' %}

 {% block titrepage %}Admission des candidats{% endblock %}

{% block centre %}
<h1>{{ formation.nom }}</h1>

<h3>Chiffres actuels :</h3>

<ul>
<li>Admis : {{NBADMIS}} <em>({{PRCADMIS}}{% verbatim %}%{% endverbatim %})</em></li>
<li>En liste complémentaire : {{NBLA}} <em>({{PRCLA}}{% verbatim %}%{% endverbatim %})</em></li>
<li>Refusés : {{NBREFUS}} <em>({{PRCREFUS}}{% verbatim %}%{% endverbatim %})</em></li>
<li>Sans décision : {{NBNONDEC}} <em>({{PRCNONDEC}}{% verbatim %}%{% endverbatim %})</em></li>
<li>En attente de validation : {{NBNONVAL}} <em>({{PRCNONVAL}}{% verbatim %}%{% endverbatim %})</em></li>
</ul>

<div id="choix">

<p><em>La recherche est possible, soit à partir du numéro de dossier (5 derniers chiffres), soit par nom ou encore par la première lettre du nom.</em></p>

<form name="f" action="">

<span class="forminput"><label for="recherche_id_dossier">Numéro de dossier <font size="-1"><em>(5 derniers chiffres)</em></font></label> <input name="recherche_id_dossier" type="text" size="5" maxlength="5" /></span> <input type="submit" value="Lancer la recherche" />

<br />
<strong>ou</strong>
<br />

<span class="forminput"><label for="recherche_mot_nom">Nom <font size="-1"><em>(ou 1ères lettres du nom)</em></font></label> <input name="recherche_mot_nom" type="text" size="12" maxlength="25" /></span> <input type="submit" value="Lancer la recherche" />

<br />
<strong>ou</strong>
<br />

<span class="forminput"><a href="?recherche_mot_nom=A">A</a> <a href="?recherche_mot_nom=B">B</a> <a href="?recherche_mot_nom=C">C</a> <a href="?recherche_mot_nom=D">D</a> <a href="?recherche_mot_nom=E">E</a> <a href="?recherche_mot_nom=F">F</a> <a href="?recherche_mot_nom=G">G</a> <a href="?recherche_mot_nom=H">H</a> <a href="?recherche_mot_nom=I">I</a> <a href="?recherche_mot_nom=J">J</a> <a href="?recherche_mot_nom=K">K</a> <a href="?recherche_mot_nom=L">L</a> <a href="?recherche_mot_nom=M">M</a> <a href="?recherche_mot_nom=N">N</a> <a href="?recherche_mot_nom=O">O</a> <a href="?recherche_mot_nom=P">P</a> <a href="?recherche_mot_nom=Q">Q</a> <a href="?recherche_mot_nom=R">R</a> <a href="?recherche_mot_nom=S">S</a> <a href="?recherche_mot_nom=T">T</a> <a href="?recherche_mot_nom=U">U</a> <a href="?recherche_mot_nom=V">V</a> <a href="?recherche_mot_nom=W">W</a> <a href="?recherche_mot_nom=X">X</a> <a href="?recherche_mot_nom=Y">Y</a> <a href="?recherche_mot_nom=Z">Z</a></span> </form>
</div>

<div id="url-retour">
<a href="{{ path('campagne', {'id_campagne':campagne.id}) }}">Retour</a>
</div>

<hr />

<form name="g" action="{{ path('admissionconfirm', {'id_campagne':campagne.id, 'id_formation':formation.id}) }}" method="post"><div id="result">

<div class="button"><input type="submit" value="ENVOYER" /></div>

<table>
<tr><th></th><th>Civilité</th><th>Nom</th><th>Date naiss. / Num. dossier</th><th>Email / Spécialité</th><th>Diplôme</th><th>Statut</th><th>Adm./L.A./Ref.</th></tr>
{% for candidat in candidats %}
<tr class="candidat"><td><a href="" onclick="javascript:deplie({{candidat.id}})">+</a></td><td>{{candidat.civilite|replace({"f":"Madame", "m":"Monsieur"})}}</td><td>{{candidat.nom|upper}} {{candidat.prenom|title}}</td><td>{{candidat.datenaiss|date("d/m/Y")}}</td><td><input name="email{{candidat.id}}" size="35" value="{{candidat.email}}" /></td><td><span class="diplome">{% if candidat.diplome %}{{candidat.diplome.etape}}{% endif %}</span></td><td class="nostyle"></td></tr>
{% for candidature in candidat.candidatures %}
<tr class="dossier" display="{{display}}"><td colspan="3"></td><td>{% if candidature.formation.id != id_formation %}<font size="-1"><em>{% endif %}{{prefixe_dossier}}{{"%05d"|format(candidature.id)}}{% if candidature.formation.id != id_formation %}</em></font>{% endif %}</td><td colspan="2">{% if candidature.formation.id != id_formation %}{% if candidature.resultat.code > 2 %}<a href="../0/{{candidature.formation.id}}">{% else %}<a href="../../validation/0/{{candidature.formation.id}}">{% endif %}<font size="-1"><em>{% endif %}{{candidature.formation.nom}}{% if candidature.formation.id != id_formation %}</em></font></a>{% endif %}</td><td class="statut">{{candidature.resultat.code|replace({"0":"téléch.", "1":"refusé", "2":"incompl.", "3":"compl.sf sem.", "4":"vérif.", "5":"convoc.", "6":"l.a.", "7":"admis"})|raw}}</td>
{% if candidature.formation.id != id_formation %}<td>&nbsp;</td><td>&nbsp;</td>{% endif %}
{% if candidature.resultat.code==1 %}<td colspan="2"><small><em>({{candidature.motifRefus|truncate(9)}})</em></small></td>{% endif %}
{% if candidature.resultat.code==5 %}<td class="check1"><span class="admis"><input name="resul{{candidature.id}}" value="admis" type="radio"/></span><span class="la"><input name="resul{{candidature.id}}" value="la" type="radio" /></span><span class="refus"><input name="resul{{candidature.id}}" value="refus" type="radio" /></span></td><td colspan="2"><small>le {{candidature.convocation.date}} à {{candidature.convocation.heure}}, s. {{candidature.convocation.lieu}}</small></td>{% endif %}
{% if candidature.resultat.code==7 %}<td>&nbsp;</td><td>&nbsp;</td>{% endif %}
{% if candidature.formation.id == id_formation %}
{% if candidature.resultat.code==4 or candidature.resultat.code==3 %}<td class="check1"><span class="admis"><input name="resul{{candidature.id}}" value="admis" type="radio"/></span><span class="la"><input name="resul{{candidature.id}}" value="la" type="radio" /></span><span class="refus"><input name="resul{{candidature.id}}" value="refus" type="radio" /></span></td>
{% if campagne.convocationAvantAdmission %}<td class="check2">&nbsp;</td><td class="check2">conv. <input name="resul{{candidature.id}}" value="convoc" type="radio" {{candidature.convocation}} /> le <input class="date" name="date{{candidature.id}}" type="text" size="8" {% if candidature.convocation %}value="{{candidature.convocation.date}}"{% endif %} /> à <input class="heure" name="heure{{candidature.id}}" type="text" size="4" {% if candidature.convocation %}value="{{candidature.convocation.heure}}"{% endif %} /> s. <input class="date" name="lieu{{candidature.id}}" type="text" size="5" {% if candidature.convocation %}value="{{candidature.convocation.lieu}}"{% endif %} /></td>{% endif %}
{% endif %}
{% if candidature.resultat.code==6 %}<td class="check1"><span class="admis"><input name="resul{{candidature.id}}" value="admis" type="radio"/></span><span class="la">&nbsp;&nbsp;</span><span class="refus"><input name="resul{{candidature.id}}" value="refus" type="radio" /></span></td><td class="check2">&nbsp;</td>{% endif %}
{% endif %}</tr>{% endfor %}
{% endfor %}</table>

<div class="button"><input type="submit" value="ENVOYER" /></div>

</div></form>

{% endblock %}

src/AideBundle/Resources/views/Backoffice/admissionconfirm.html.twig
{% extends '::suivi.html.twig' %}

 {% block titrepage %}Admission des candidats : confirmation avant envoi des résultats{% endblock %}

{% block centre %}
<h1>{{ formation.nom }}</h1>

<div id="url-retour">
<a href="{{ path('admissioncancel', {'id_campagne':campagne.id, 'id_formation':formation.id}) }}">Retour</a>
</div>

<hr />

<form name="f" action="{{ path('admission', {'id_campagne':campagne.id, 'id_formation':formation.id}) }}" method="post"><div id="result">

<ul>{% for candidature in candidatures_a_admettre %}
  {% if loop.first %}<div class="admis"><p><strong>Candidatures que vous vous apprêtez à <font color="green" size="+1">admettre</font></strong></p><ul>{% endif %}
  <li>{{prefixe_dossier}}{{"%05d"|format(candidature.id)}} - {{candidature.candidat.nom}} {{candidature.candidat.prenom}} - {{candidature.formation.nom}}</li>
  {% if  loop.last  %}</ul></div>{% endif %}
{% endfor %}</ul>

<ul>{% for candidature in candidatures_a_la %}
  {% if loop.first %}<div class="la"><p><strong>Candidatures que vous vous apprêtez à <font color="orange" size="+1">placer en liste complémentaire</font></strong></p><ul>{% endif %}
  <li>{{prefixe_dossier}}{{"%05d"|format(candidature.id)}} - {{candidature.candidat.nom}} {{candidature.candidat.prenom}} - {{candidature.formation.nom}}</li>
  {% if  loop.last  %}</ul></div>{% endif %}
{% endfor %}</ul>

<ul>{% for candidature in candidatures_a_convoquer %}
  {% if loop.first %}<div class="convoc"><p><strong>Candidats que vous vous apprêtez à <font color="grey" size="+1">convoquer</font></strong></p><ul>{% endif %}
  <li>{{prefixe_dossier}}{{"%05d"|format(candidature.id)}} - {{candidature.candidat.nom}} {{candidature.candidat.prenom}} - {{candidature.formation.nom}} - le {{candidature.convocation.date}} à {{candidature.convocation.heure}}, s. {{candidature.convocation.lieu}}</li>
  {% if  loop.last  %}</ul></div>{% endif %}
{% endfor %}</ul>

<ul>{% for candidature in candidatures_a_refuser %}
  {% if loop.first %}<div class="refus"><p><strong>Candidatures que vous vous apprêtez à <font color="red" size="+1">refuser</font></strong></p><ul>{% endif %}
  <li>{{prefixe_dossier}}{{"%05d"|format(candidature.id)}} - {{candidature.candidat.nom}} {{candidature.candidat.prenom}} - {{candidature.formation.nom}} <select name="motif{{candidature.id}}"><option value="">Motif</option>
 {% for motif in motifs_refus %}<option value="{{motif.code}}">{{motif.libelle}}</option>{% endfor %}
</select></li>
  {% if  loop.last  %}</ul></div>{% endif %}
{% endfor %}</ul>


<p>Après avoir <strong><u>relu attentivement</u></strong>, vous pouvez maintenant confirmer en pressant ce bouton ----&gt;&nbsp;
<input type="submit" value="OK" /></p></form>

<form name="r" action="{{ path('admissioncancel', {'id_campagne':campagne.id, 'id_formation':formation.id}) }}"><p><em>Ou</em>, si quelque chose ne va pas, pour revenir à la page précédente, cliquez ici ----&gt;&nbsp;<input type="submit" value="RETOUR" /></p></form>
</div>

{% endblock %}

src/AideBundle/Resources/views/Backoffice/campagne.html.twig
 {% extends '::suivi.html.twig' %}

 {% block titrepage %}Suivi des candidatures : {{ campagne.nom }}{% endblock %}

{% block droite %}
{% if is_granted('ROLE_ADMIN') %}
    <em><a href="{{ path('admin') }}/dashboard">Aller à l'administration de l'application</a></em>&nbsp;/
{% endif %}
&nbsp;<a href="{{ path('_logout') }}">Se déconnecter</a>
{% endblock %}

 {% block centre %}

<form name="f" action="">Trier par <select name="tri"><option value="code" {{ selected_code }}>code de la spécialité</option><option value="label" {{ selected_label }}>libellé de la spécialité</option><option value="telech" {{ selected_telech }}>nombre de candidatures</option></select></form>

<p><em>Aujourd'hui, total dossiers téléchargés = <strong>{{ total_telecharges }}</strong></em></p>

<table><tr><th><a href="{{ path('campagneavectri', {'id_campagne':campagne.id, 'tri':'bycode'}) }}">Code</a></th>
<th><a href="{{ path('campagneavectri', {'id_campagne':campagne.id, 'tri':'bylabel'}) }}">Libellé</a></th>
<th><a href="{{ path('campagneavectri', {'id_campagne':campagne.id, 'tri':'bytelech'}) }}">Téléchargés</a></th>
<th><a href="{{ path('campagneavectri', {'id_campagne':campagne.id, 'tri':'byvalid'}) }}">Validés</a></th>
<th><a href="{{ path('campagneavectri', {'id_campagne':campagne.id, 'tri':'byvalidprc'}) }}">% Val.</a></th>
<th>Déc.</th><th>% Déc.</th><th></th><th></th></tr>

{% for ligne in lignes %}
<tr><td>{{ ligne.formation.code }}</td><td>{{ ligne.formation.nom }}</td>
<td><a href="{{ path('validation', {'id_campagne':campagne.id, 'id_formation':ligne.formation.id}) }}">{{ ligne.nb_total }}</a></td>
<td><a href="{{ path('admission', {'id_campagne':campagne.id, 'id_formation':ligne.formation.id}) }}">{{ ligne.nb_valides }}</a></td>
<td>{{ ligne.prc_valides }}</td>
<td>{{ ligne.nb_decision }}</td>
<td>{{ ligne.prc_decision }}</td>
<td><a href="{{ path('liste', {'id_campagne':campagne.id, 'id_formation':ligne.formation.id}) }}"><em>Liste</em></a></td>
<td><a href="{{ path('tableau', {'id_campagne':campagne.id, 'id_formation':ligne.formation.id}) }}"><em>Tableau</em></a></td></tr>
{% endfor %}
<tr><td>&nbsp;</td><td>-----------------</td><td>---</td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>&nbsp;</td><td>TOTAL</td><td>{{ total_telecharges }}</td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
</table>

 {% endblock %}

src/AideBundle/Resources/views/Backoffice/emailadmission.txt.twig
{{candidat.civilite|replace({"f":"Madame", "m":"Monsieur"})}} {{candidat.nom}},

La commission pédagogique a émis un avis favorable à votre candidature
pour la formation

     	 {{formation.nom}}

Afin de nous permettre de vous accueillir dans les meilleures
conditions, nous vous demandons de bien vouloir vous conformer à la
procédure suivante.

Les inscriptions administratives auront lieu du {{campagne.dateouvertureinscriptions|date('d/m')}} au {{campagne.dateclotureinscriptions|date('d/m')}},
entre 9H30 et 11H30 ou entre 13H30 et 15H45 au bureau {{campagne.bureauinscription}}.

Muni-e obligatoirement de :

  * Dossier ci-joint, dûment renseigné et complété
  * *Impérativement toutes* les pièces demandées
  * Un moyen de paiement (pas d'espèces, carte bleue de préférence)
  * La fiche pédagogique de l'année 2017-2018, que vous aurez téléchargée
    par le biais du lien suivant :
    http://www.jm.u-psud.fr/fr/les_formations/droit/licence_de_droit.html
    ou
    http://www.jm.u-psud.fr/fr/les_formations/economie_gestion/parcours_economie_gestion.html

à l'adresse suivante :

  Faculté Jean Monnet
  54 boulevard Desgranges
  Bâtiment B - Rez de chaussée-haut - Bureau B1
  92330 Sceaux

*Tout dossier incomplet sera rejeté*

Par le biais des liens suivants vous trouverez toutes les informations 
nécessaires concernant la sécurité sociale étudiante, les mutuelles et 
assurances

http://www.smerep.fr

http://www.lmde.fr/

Cordialement,
--
UFR Droit - Economie et Gestion
{{bureau.service}}
{{bureau.description}}
Bureau {{bureau.code}}
54 Boulevard Desgranges
92330 Sceaux 

src/AideBundle/Resources/views/Backoffice/emailannulation.txt.twig
{{candidat.civilite|replace({"f":"Madame", "m":"Monsieur"})}},

Vous avez demandé l'annulation de votre dossier de candidature pour la formation {{formation.nom}}.

Nous vous informons que nous avons procédé à cette annulation.

Cordialement.

--
UFR Droit - Economie et Gestion
{{bureau.service}}
{{bureau.description}}
Bureau {{bureau.code}}
54 Boulevard Desgranges
92330 Sceaux 

src/AideBundle/Resources/views/Backoffice/emailconvocation.txt.twig
{{candidat.civilite|replace({"f":"Madame", "m":"Monsieur"})}},

Comme suite à votre demande de candidature en

      *{{formation.nom}}*

je vous informe que le jury de sélection vous recevra pour un entretien

*le {{convocation.date}} à {{convocation.heure}}*

*en salle {{convocation.lieu}}*

Adresse : Faculté Jean Monnet
54 bd Desgranges, 92330 SCEAUX

(Prendre le RER B direction ROBINSON - descendre au terminus - à 5 min de la gare)

Veuillez confirmer votre présence à l'entretien, *par retour de courriel*.

Je vous prie de croire, {{candidat.civilite|replace({"f":"Madame", "m":"Monsieur"})}}, à l'assurance de ma considération distinguée.


Le Responsable de la formation

--
UFR Droit - Economie et Gestion
{{bureau.service}}
{{bureau.description}}
Bureau {{bureau.code}}
54 Boulevard Desgranges
92330 Sceaux

src/AideBundle/Resources/views/Backoffice/emailincomplet.txt.twig
{{candidat.civilite|replace({"f":"Madame", "m":"Monsieur"})}},

Nous avons réceptionné votre dossier pour la formation 

*{{formation.nom}}*

et lui avons attribué le numéro suivant : *{{prefixe_dossier}}{{"%05d"|format(candidature.id)}}*

Malheureusement, votre dossier est incomplet.

Vous devez nous transmettre, dans les plus brefs délais ou/et dès 
que vous serez en possession du ou des document(s) demandé(s) :

{{liste_piecesmanquantes}}{{piecesmanquantes_libres}}

Nous vous remercions de préciser, pour tout envoi, vos nom, prénom, 
*formation demandée et numéro de dossier*.
Sans cette identification, les pièces ne seront pas prises en compte 
et votre dossier sera définitivement irrecevable.

--
UFR Droit - Économie et Gestion
{{bureau.service}}
{{bureau.description}}
Bureau {{bureau.code}}
54 Boulevard Desgranges
92330 Sceaux 

src/AideBundle/Resources/views/Backoffice/emailla.txt.twig
{{candidat.civilite|replace({"f":"Madame", "m":"Monsieur"})}},

Comme suite à votre candidature en

{{formation.nom}}

je vous informe que le jury de sélection vous a 
inscrit{{candidat.civilite|replace({"f":"e", "m":""})}} sur la liste complémentaire.

A la clôture des inscriptions des étudiants de la liste principale, nous
vous contacterons pour vous indiquer la suite accordée à votre candidature.

Cordialement.

--
UFR Droit - Economie et Gestion
{{bureau.service}}
{{bureau.description}}
Bureau {{bureau.code}}
54 Boulevard Desgranges
92330 Sceaux 